---
permalink: sm-storage/decide-to-use-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: create, volumes, using, either, pool, group, selection, depend, primarily, key, storage, requirements, expect, workload, performance, data, protection 
summary: Es posible crear volúmenes a través de un pool o de un grupo de volúmenes. La mejor selección depende principalmente de los requisitos de almacenamiento clave, como la carga de trabajo de I/o esperada, los requisitos de rendimiento y los requisitos de protección de datos. 
---
= Decidir si se utilizará un pool y un grupo de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible crear volúmenes a través de un pool o de un grupo de volúmenes. La mejor selección depende principalmente de los requisitos de almacenamiento clave, como la carga de trabajo de I/o esperada, los requisitos de rendimiento y los requisitos de protección de datos.



== Motivos para elegir un pool o un grupo de volúmenes

*Elegir una piscina*

* Si necesita recompilaciones de la unidad más rápidas y gestión de almacenamiento simplificada, requiere volúmenes finos y/o posee una carga de trabajo altamente aleatoria.
* Si desea distribuir los datos para cada volumen de manera aleatoria en una serie de unidades que componen el pool.
+
No es posible configurar o cambiar el nivel de RAID de los pools ni los volúmenes en los pools. Los pools utilizan RAID nivel 6.



*Elija un grupo de volúmenes*

* Si necesita el máximo ancho de banda del sistema, la capacidad para modificar la configuración de almacenamiento y una carga de trabajo altamente secuencial.
* Si desea distribuir datos en las unidades según un nivel de RAID. Es posible especificar el nivel de RAID al crear el grupo de volúmenes.
* Si desea escribir los datos para cada volumen secuencialmente a través del conjunto de unidades que componen el grupo de volúmenes.


[NOTE]
====
Debido a que los pools pueden coexistir con los grupos de volúmenes, una cabina de almacenamiento puede incluir tanto pools como grupos de volúmenes.

====


== Diferencias de funciones entre pools y grupos de volúmenes

En la siguiente tabla, se incluye una comparación entre grupos de volúmenes y pools.

[cols="3*"]
|===
| Uso | Piscina | Grupo de volúmenes 


 a| 
Carga de trabajo aleatoria
 a| 
Mejor
 a| 
Muy bien



 a| 
Carga de trabajo secuencial
 a| 
Muy bien
 a| 
Mejor



 a| 
Tiempo de recompilación de la unidad
 a| 
Rápido
 a| 
Más lento



 a| 
Rendimiento (modo óptimo)
 a| 
Bueno: Ideal para carga de trabajo aleatoria de bloques pequeños
 a| 
Bueno: Ideal para carga de trabajo secuencial de bloques grandes



 a| 
Rendimiento (modo de recompilación de la unidad)
 a| 
Mejor: Generalmente mejor que RAID 6
 a| 
Degradado: Caída de rendimiento de hasta el 40 %



 a| 
Fallos de unidad múltiples
 a| 
Mayor protección de datos: Recompilaciones priorizadas y más rápidas
 a| 
Menor protección de datos: Recompilaciones más lentas, mayor riesgo de pérdida de datos



 a| 
Agregar unidades
 a| 
Más rápido: Añadir al pool sobre la marcha
 a| 
Más lento: Requiere una operación de expansión de capacidad dinámica



 a| 
Compatibilidad con volúmenes finos
 a| 
Sí
 a| 
No



 a| 
Compatibilidad con discos de estado sólido (SSD)
 a| 
Sí
 a| 
Sí



 a| 
Administración simplificada
 a| 
Sí: No es necesario asignar piezas de repuesto ni configurar RAID
 a| 
No: Es necesario asignar piezas de repuesto y configurar RAID



 a| 
Rendimiento ajustable
 a| 
No
 a| 
Sí

|===