---
permalink: sm-storage/what-is-the-default-cluster.html 
sidebar: sidebar 
keywords: default, cluster, system, defined, entity, allow, unassociated, host, bus, adapter, port, identifier, logged, storage, array, gain, access, volumes, assign, physically, installed, particular 
summary: 'El clúster predeterminado es una entidad definida por el sistema que permite que cualquier identificador de puerto de host de adaptador de bus de host (HBA) no asociado que haya iniciado sesión en la cabina de almacenamiento acceda a cualquier volumen asignado al clúster predeterminado. Un identificador de puerto de host no asociado es un puerto de host que si bien está físicamente instalado en un host y tiene sesión iniciada en la cabina de almacenamiento, no está asociado de forma lógica con ningún host en particular.' 
---
= ¿Qué es el clúster predeterminado?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El clúster predeterminado es una entidad definida por el sistema que permite que cualquier identificador de puerto de host de adaptador de bus de host (HBA) no asociado que haya iniciado sesión en la cabina de almacenamiento acceda a cualquier volumen asignado al clúster predeterminado. Un identificador de puerto de host no asociado es un puerto de host que si bien está físicamente instalado en un host y tiene sesión iniciada en la cabina de almacenamiento, no está asociado de forma lógica con ningún host en particular.

[NOTE]
====
Si desea que los hosts tengan acceso específico a ciertos volúmenes en la cabina de almacenamiento, se debe _no_ utilizar el clúster predeterminado. En cambio, se deben asociar los identificadores del puerto de host con sus hosts correspondientes. Esto puede realizarse de forma manual mediante System Manager durante la operación Create Host, o bien de forma automática mediante el agente de contexto de host (HCA) instalado en cada host. A continuación, se deben asignar los volúmenes a un host individual o a un clúster de hosts.

====
Se debe _solo_ usar el clúster predeterminado en situaciones especiales en las que el entorno de almacenamiento externo sea propicio para permitir que todos los hosts y todos los identificadores de puerto de host con sesión iniciada conectados a la cabina de almacenamiento tengan acceso a todos los volúmenes (modo de acceso total) Sin dar a conocer específicamente los hosts a la cabina de almacenamiento o a System Manager.

Inicialmente, se pueden asignar los volúmenes solo al clúster predeterminado a través de la interfaz de línea de comandos (CLI). Sin embargo, luego de asignar al menos un volumen al clúster predeterminado, esta entidad (denominada clúster predeterminado) se muestra en System Manager, y entonces se podrá utilizar System Manager para gestionar esta entidad.
