---
permalink: sm-mirroring/re-synchronize-mirror-consistency-group-manually.html 
sidebar: sidebar 
keywords: manual, mirror, pair, consistency, group 
summary: Es posible iniciar manualmente la resincronización de todas las parejas reflejadas dentro de un grupo de coherencia de reflejos. 
---
= Volver a sincronizar manualmente un grupo de coherencia de reflejos
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible iniciar manualmente la resincronización de todas las parejas reflejadas dentro de un grupo de coherencia de reflejos.

.Pasos
. Seleccione *MENU:Storage[Synchronous Mirroring]*.
. Seleccione la ficha *grupos de consistencia de mirroring*.
+
Se muestra la tabla Grupo de coherencia de reflejos donde se detallan los grupos de coherencia de reflejos asociados con la cabina de almacenamiento.

. Seleccione el grupo de coherencia de reflejos que desea volver a sincronizar y, a continuación, seleccione *menú:más[Resincronizar manualmente]*.
+
El sistema muestra una confirmación.

. Seleccione *Sí* para confirmar.


.Resultados
El sistema ejecuta las siguientes acciones:

* Inicia la resincronización de los datos de todas las parejas reflejadas dentro del grupo de coherencia de reflejos que se seleccionó.
* Actualiza los datos modificados de la cabina de almacenamiento local a la cabina de almacenamiento remota.

