---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: configure, storage, array, administrator, password, protect, unauthorize, access 
summary: Debe configurar la cabina de almacenamiento con una contraseña de administrador para protegerla del acceso no autorizado. 
---
= Protección con contraseña de administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar la cabina de almacenamiento con una contraseña de administrador para protegerla del acceso no autorizado.



== Establecer una contraseña de administrador

Al establecer una contraseña de administrador para la cabina de almacenamiento, la cabina queda protegida de usuarios que ejecutan comandos destructivos sin saberlo o con malas intenciones. Se le solicitará que establezca una contraseña de administrador cuando inicie System Manager por primera vez.

Hay una contraseña de administrador que comparten todos los usuarios. Cualquier usuario que tenga esta contraseña podrá realizar cambios de configuración en la cabina de almacenamiento, por ejemplo, añadir, cambiar o quitar objetos o la configuración.



== Introducir la contraseña

El sistema solicita la contraseña una sola vez durante una misma sesión de gestión. Una sesión finaliza a los 20 minutos de inactividad; después de ese período, deberá introducir la contraseña otra vez.

Si otro usuario que esté gestionando la misma cabina de almacenamiento desde otro cliente de gestión cambia la contraseña mientras su sesión está en progreso, se le solicitará una contraseña la próxima vez que intente realizar una operación de configuración o de vista.

Por razones de seguridad, puede intentar introducir una contraseña solo cinco veces antes de que la cabina de almacenamiento quede bloqueada. En este estado, la cabina de almacenamiento rechaza cualquier nuevo intento de introducir una contraseña. Se deben esperar 10 minutos para que la cabina de almacenamiento se restablezca y pueda volver a introducir una contraseña.



== Quitar unidades que están protegidas con contraseña

La contraseña se almacena en un área reservada de cada unidad de la cabina de almacenamiento. Si se quitan todas las unidades de la cabina de almacenamiento, la contraseña ya no funciona. Para corregir esta situación, se debe volver a instalar una de las unidades originales en la cabina de almacenamiento.



== Quitar la protección con contraseña

Si ya no desea que los comandos estén protegidos con contraseña, introduzca la contraseña de administrador actual y deje los cuadros de texto de la contraseña nueva en blanco.

[NOTE]
====
Si se ejecutan comandos de configuración en una cabina de almacenamiento, se pueden producir daños graves, incluso la pérdida de datos. Por este motivo, siempre debe configurar una contraseña de administrador para la cabina de almacenamiento. Use una contraseña de administrador de al menos 15 caracteres alfanuméricos para reforzar la seguridad.

====