---
permalink: sm-settings/nvme-terminology.html 
sidebar: sidebar 
keywords: nvme, terms, storage array 
summary: Conozca la forma en que los términos de NVMe se aplican a su cabina de almacenamiento. 
---
= Terminología de NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conozca la forma en que los términos de NVMe se aplican a su cabina de almacenamiento.

[cols="1a,3a"]
|===
| Duración | Descripción 


 a| 
Estructura
 a| 
InfiniBand (IB) es una norma de comunicación para la transmisión de datos entre servidores de alto rendimiento y sistemas de almacenamiento.



 a| 
Espacio de nombres
 a| 
Un espacio de nombres es almacenamiento NVM que se formateó para el acceso en bloque. Es análogo a una unidad lógica en SCSI, que se relaciona con un volumen en la cabina de almacenamiento.



 a| 
Identificador de espacio de nombres
 a| 
El ID del espacio de nombres es el identificador único de la controladora NVMe para el espacio de nombres y se puede configurar con un valor entre 1 y 255. Es análogo a un número de unidad lógica (LUN) en SCSI.



 a| 
NQN
 a| 
El nombre completo de NVMe (NQN) se utiliza para identificar el destino de almacenamiento remoto (la cabina de almacenamiento).



 a| 
NVM
 a| 
La memoria no volátil (NVM) es la memoria persistente utilizada en muchos tipos de dispositivos de almacenamiento.



 a| 
NVMe
 a| 
La memoria no volátil rápida (NVMe) es una interfaz designada para dispositivos de almacenamiento basados en flash, por ejemplo, unidades SSD. NVMe reduce la sobrecarga de I/o e incluye mejoras de rendimiento, en comparación con las interfaces de dispositivos lógicos anteriores.



 a| 
NVMe-of
 a| 
La memoria no volátil rápida sobre estructuras (NVMe-of) es una especificación que permite el funcionamiento de comandos y la transferencia de datos de NVMe en una red entre un host y el almacenamiento.



 a| 
Controladora NVMe
 a| 
Se crea una controladora NVMe durante el proceso de conexión del host. Esta ofrece una ruta de acceso entre un host y los espacios de nombres en la cabina de almacenamiento.



 a| 
Cola NVMe
 a| 
Una cola que se utiliza para pasar comandos y mensajes a través de la interfaz de NVMe.



 a| 
Subsistema NVMe
 a| 
La cabina de almacenamiento con una conexión NVMe.



 a| 
RDMA
 a| 
El acceso remoto a memoria directa (RDMA) permite un movimiento de datos más directo hacia y desde un servidor gracias a la implementación de un protocolo de transporte en el hardware de la tarjeta de interfaz de red (NIC).



 a| 
Roce
 a| 
RDMA over Converged Ethernet (roce) es un protocolo de red que permite el acceso remoto a memoria directa (RDMA) sobre una red Ethernet.



 a| 
SSD
 a| 
Los discos de estado sólido (SSD) son dispositivos de almacenamiento de datos que usan memoria de estado sólido (flash) para almacenar datos en forma persistente. Los SSD emulan las unidades de discos duros convencionales y están disponibles con las mismas interfaces que usan las unidades de disco duro.

|===