---
permalink: sm-settings/use-ca-signed-certificates-for-controllers.html 
sidebar: sidebar 
keywords: ca signed certificate, secure communication, controller, browser, system manager 
summary: Es posible obtener certificados firmados por CA para establecer comunicaciones seguras entre las controladoras y el explorador que se utiliza para acceder a System Manager. 
---
= Use certificados firmados por CA para las controladoras
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible obtener certificados firmados por CA para establecer comunicaciones seguras entre las controladoras y el explorador que se utiliza para acceder a System Manager.

.Antes de empezar
* Debe iniciar sesión con un perfil de usuario que cuente con permisos de administración de seguridad. De lo contrario, no se mostrarán las funciones de certificación.


.Acerca de esta tarea
El uso de certificados firmados por CA implica un procedimiento de tres pasos.



== Paso 1: Complete y envíe una CSR para las controladoras

Primero, es necesario generar un archivo de solicitud de firma de certificación (CSR) para cada controladora de la cabina de almacenamiento y, a continuación, enviar los archivos a la entidad de certificación (CA).

.Antes de empezar
* Debe conocer la dirección IP o el nombre DNS de cada controladora.


.Acerca de esta tarea
La CSR proporciona información sobre su organización, la dirección IP o el nombre DNS de la controladora, y una pareja de claves para identificar el servidor web de la controladora. Durante esta tarea, se genera un archivo CSR si solo existe una controladora en la cabina de almacenamiento y dos archivos CSR si existen dos controladoras.

[CAUTION]
====
No genere una nueva CSR después de enviar una a la CA. Al generar una CSR, el sistema crea una pareja de claves pública y privada. La clave pública se incluye en la CSR, mientras que la clave privada se conserva en el almacén de claves. Al recibir los certificados firmados e importarlos al almacén de claves, el sistema se asegura de que las claves pública y privada sean la pareja original. Por lo tanto, no debe generar una nueva CSR después de enviar una a la CA. Si lo hace, las controladoras generarán claves nuevas y los certificados que reciba de la CA no funcionarán.

====
.Pasos
. Seleccione *MENU:Settings[Certificates]*.
. En la ficha *Gestión de matrices*, seleccione *completar CSR*.
+
[NOTE]
====
Si aparece un cuadro de diálogo que le pide que acepte un certificado autofirmado para el segundo controlador, haga clic en *Aceptar certificado autofirmado* para continuar.

====
. Introduzca la siguiente información y, a continuación, haga clic en *Siguiente*:
+
** *Organización* -- el nombre completo y legal de su empresa u organización. Incluya sufijos, como Inc. O Corp
** *Unidad organizativa (opcional)* -- la división de su organización que maneja el certificado.
** *Ciudad/localidad* -- Ciudad en la que se encuentra la matriz de almacenamiento o el negocio.
** *Estado/Región (opcional)* -- el estado o región donde está ubicada la matriz de almacenamiento o el negocio.
** *Código ISO de país*: Código ISO (Organización Internacional de Normalización) de dos dígitos de su país, por ejemplo, US.


+
[CAUTION]
====
Algunos campos pueden autocompletarse con la información adecuada, como la dirección IP de la controladora. No cambie los valores autocompletados a menos que esté seguro de que son incorrectos. Por ejemplo, si todavía no ha completado una CSR, la dirección IP de la controladora se establecerá en "'localhost'". En ese caso, deberá cambiar «'localhost'» por el nombre DNS o la dirección IP del controlador.

====
. Verifique o introduzca la siguiente información acerca de la controladora A en su cabina de almacenamiento:
+
** *Controller un nombre común* -- la dirección IP o el nombre DNS del controlador A se muestran de manera predeterminada. Compruebe que la dirección sea correcta; debe coincidir exactamente con lo que escribe para acceder a System Manager en el explorador.
** *Controller a Alternate IP address* -- Si el nombre común es una dirección IP, puede opcionalmente escribir cualquier dirección IP adicional o alias para el controlador A. Si va a introducir varios datos, use un formato delimitado por comas.
** *Nombre DNS alternativo del controlador a* -- Si el nombre común es un nombre DNS, introduzca cualquier nombre DNS adicional para el controlador A. Si va a introducir varios datos, use un formato delimitado por comas. Si no hay nombres DNS alternativos, pero especificó un nombre DNS en el primer campo, copie ese nombre aquí. Si la cabina de almacenamiento sólo tiene una controladora, el botón *Finalizar* estará disponible. Si la cabina de almacenamiento tiene dos controladores, el botón *Siguiente* estará disponible.


+
[NOTE]
====
No haga clic en el enlace *Omitir este paso* cuando cree inicialmente una solicitud CSR. El enlace se proporciona para situaciones de recuperación de errores. En raras ocasiones, una solicitud CSR puede generar errores en una controladora, pero no en la otra. Este enlace permite omitir el paso para crear una solicitud CSR en la controladora A si ya está definida, y continuar hacia el siguiente paso para volver a crear una solicitud CSR en la controladora B.

====
. Si sólo hay un controlador, haga clic en *Finalizar*. Si hay dos controladores, haga clic en *Siguiente* para introducir información para el controlador B (igual que el anterior) y, a continuación, haga clic en *Finalizar*.
+
Para una sola controladora, se descarga un archivo CSR en el sistema local. Para controladoras dobles, se descargan dos archivos CSR. La ubicación de la carpeta de la descarga depende del explorador.

. Busque los archivos CSR descargados. La ubicación de la carpeta depende del explorador.
. Envíe los archivos CSR a una CA y solicite certificados firmados en formato PEM.
. Espere a que la CA devuelva los certificados y vaya a. <<Paso 2: Importe los certificados firmados para las controladoras>>.




== Paso 2: Importe los certificados firmados para las controladoras

Después de recibir los certificados firmados, es necesario importar los archivos para las controladoras.

.Antes de empezar
* La CA devolvió archivos de certificado firmados.
* Los archivos se encuentran disponibles en el sistema local.
* Si la CA proporcionó un certificado encadenado (por ejemplo, un archivo .p7b), debe desempaquetar el archivo encadenado en archivos individuales: El certificado raíz, el o los certificados intermedios y los certificados de servidor que identifican a las controladoras. Puede utilizar Windows `certmgr` Utilidad para desempaquetar los archivos (haga clic con el botón derecho y seleccione *menú:todas las tareas[Exportar]*). Una vez completadas las exportaciones, se mostrará un archivo CER para cada archivo de certificado de la cadena.


.Acerca de esta tarea
En esta tarea, se describe la manera de cargar los archivos de certificado.

.Pasos
. Seleccione *MENU:Settings[Certificates]*.
. En la ficha *Administración de matrices*, seleccione *Importar*.
+
Se abre un cuadro de diálogo para importar los archivos de certificado.

. Haga clic en los botones *examinar* para seleccionar primero el archivo raíz y los archivos intermedios y, a continuación, seleccionar cada certificado de servidor para los controladores. El archivo raíz y los archivos intermedios son los mismos para ambas controladoras. Solo los certificados de servidor son únicos para cada controladora.
+
Se muestran los nombres de los archivos en el cuadro de diálogo.

. Haga clic en *Importar*.
+
Los archivos se cargan y validan.



.Resultados
La sesión finaliza automáticamente. Debe volver a iniciar sesión para que los certificados entren en vigencia. Cuando inicia sesión nuevamente, se utiliza el nuevo certificado firmado por la CA en la sesión.
