---
permalink: sm-support/mac-transmit-and-mac-receive-statistics.html 
sidebar: sidebar 
keywords: transmit, receive, statistics, ethernet, transmit 
summary: Estadísticas de transmisión MAC y recepción MAC 
---
= Estadísticas de transmisión MAC y recepción MAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Cuando se selecciona la opción Ethernet MAC statistics, se muestran estas estadísticas de transmisión MAC. Es posible ver cada una de las estadísticas como estadísticas sin configurar o estadísticas de base.

[cols="2*"]
|===
| Estadística | Definición 


 a| 
F
 a| 
Número de marcos



 a| 
B
 a| 
Número de bytes



 a| 
MF
 a| 
Número de marcos de multidifusión



 a| 
BF
 a| 
Número de marcos de difusión



 a| 
PF
 a| 
Número de marcos en pausa



 a| 
CF
 a| 
Número de marcos de control



 a| 
FDF
 a| 
Número diferido de marcos



 a| 
ALIMENTADOS
 a| 
Número diferido de exceso de marcos



 a| 
FLC
 a| 
Número de colisiones tardías de marcos



 a| 
FA
 a| 
Número de marcos cancelados



 a| 
FSC
 a| 
Número de colisiones individuales de marcos



 a| 
FMC
 a| 
Número de varias colisiones de marcos



 a| 
FC
 a| 
Número de colisiones de marcos



 a| 
FDR
 a| 
Número de marcos descartados



 a| 
JF
 a| 
Número de trama gigante

|===
Cuando se selecciona la opción Ethernet MAC statistics, se muestran estas estadísticas de recepción MAC.

[cols="2*"]
|===
| Estadística | Definición 


 a| 
F
 a| 
Número de marcos



 a| 
B
 a| 
Número de bytes



 a| 
MF
 a| 
Número de marcos de multidifusión



 a| 
BF
 a| 
Número de marcos de difusión



 a| 
PF
 a| 
Número de marcos en pausa



 a| 
CF
 a| 
Número de marcos de control



 a| 
FLE
 a| 
Número de errores de longitud de marco



 a| 
FD
 a| 
Número de marcos descartados



 a| 
FCRCE
 a| 
Número de errores de CRC de marco



 a| 
CUOTA
 a| 
Número de errores de codificación de marco



 a| 
LFE
 a| 
Número de errores de marco grande



 a| 
SFE
 a| 
Número de errores de marco pequeño



 a| 
J
 a| 
Número de Jabber



 a| 
UCC
 a| 
Número de marcos de control desconocido



 a| 
CSE
 a| 
Número de errores de detección de portador

|===