---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: configure, santricity, unified, manager, administrator, password, protect, unauthorized, access 
summary: Debe configurar Unified Manager de SANtricity con una contraseña de administrador para proteger la instancia del acceso no autorizado. 
---
= Protección con contraseña de administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar Unified Manager de SANtricity con una contraseña de administrador para proteger la instancia del acceso no autorizado.



== Establecer una contraseña de administrador

Al configurar una contraseña de administrador, se protege al software de usuarios que ejecutan comandos destructivos sin saberlo o con malas intenciones. Se le solicitará que establezca una contraseña de administrador cuando inicie Unified Manager por primera vez.

Hay una contraseña de administrador que comparten todos los usuarios. Cualquier usuario que tenga esta contraseña puede hacer cambios en la configuración de los sistemas de almacenamiento.



== Introducir la contraseña

El software solicita la contraseña una sola vez durante una misma sesión de gestión. De forma predeterminada, una sesión finaliza a los 30 minutos de inactividad; después de ese plazo, deberá introducir la contraseña otra vez. Si lo desea, puede ajustar el tiempo de espera de la sesión.

Si otro usuario accede al software desde otro cliente de gestión y cambia la contraseña mientras su sesión está en progreso, se le solicitará a usted una contraseña la próxima vez que intente realizar una operación de configuración o de vista.

Por razones de seguridad, puede intentar introducir una contraseña solo cinco veces antes de que el software quede bloqueado. En este estado, el software rechaza cualquier nuevo intento de introducir una contraseña. Se deben esperar 10 minutos para que el software se restablezca a un estado normal y usted pueda volver a introducir una contraseña.
